# coding: utf-8

"""
    SMApi

    SecurityMetrics' Application Programming Interface  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@securitymetrics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.partner_without_links import PartnerWithoutLinks  # noqa: E501
from swagger_client.rest import ApiException


class TestPartnerWithoutLinks(unittest.TestCase):
    """PartnerWithoutLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartnerWithoutLinks(self):
        """Test PartnerWithoutLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.partner_without_links.PartnerWithoutLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
