# coding: utf-8

"""
    SMApi

    SecurityMetrics' Application Programming Interface  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@securitymetrics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.merchant_api import MerchantApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMerchantApi(unittest.TestCase):
    """MerchantApi unit test stubs"""

    def setUp(self):
        self.api = MerchantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_merchant(self):
        """Test case for create_merchant

        Create a Merchant  # noqa: E501
        """
        pass

    def test_delete_merchant(self):
        """Test case for delete_merchant

        Delete a Merchant by UUID  # noqa: E501
        """
        pass

    def test_get_merchant(self):
        """Test case for get_merchant

        Find a single Merchant using their UUID  # noqa: E501
        """
        pass

    def test_get_merchant_compliance(self):
        """Test case for get_merchant_compliance

        Find the compliance information for a single Merchant using their UUID  # noqa: E501
        """
        pass

    def test_get_merchants(self):
        """Test case for get_merchants

        Get all Merchants  # noqa: E501
        """
        pass

    def test_get_merchants_by_partner_id(self):
        """Test case for get_merchants_by_partner_id

        Get Merchants by Partner  # noqa: E501
        """
        pass

    def test_update_merchant(self):
        """Test case for update_merchant

        Update the information of a single Merchant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
