# coding: utf-8

"""
    SMApi

    SecurityMetrics' Application Programming Interface  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@securitymetrics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.partner_hierarchy_put import PartnerHierarchyPut  # noqa: E501
from swagger_client.rest import ApiException


class TestPartnerHierarchyPut(unittest.TestCase):
    """PartnerHierarchyPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartnerHierarchyPut(self):
        """Test PartnerHierarchyPut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.partner_hierarchy_put.PartnerHierarchyPut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
