# coding: utf-8

"""
    SMApi

    SecurityMetrics' Application Programming Interface  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@securitymetrics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.partner_api import PartnerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPartnerApi(unittest.TestCase):
    """PartnerApi unit test stubs"""

    def setUp(self):
        self.api = PartnerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_bank(self):
        """Test case for create_bank

        Create a Partner  # noqa: E501
        """
        pass

    def test_create_merchant(self):
        """Test case for create_merchant

        Create a Merchant  # noqa: E501
        """
        pass

    def test_get_active_campaign_list_for_bank_uuid(self):
        """Test case for get_active_campaign_list_for_bank_uuid

        Find active_campaign_emails  # noqa: E501
        """
        pass

    def test_get_merchants_by_partner_id(self):
        """Test case for get_merchants_by_partner_id

        Get Merchants by Partner  # noqa: E501
        """
        pass

    def test_get_partners(self):
        """Test case for get_partners

        Get all Partners  # noqa: E501
        """
        pass

    def test_get_partners_by_id(self):
        """Test case for get_partners_by_id

        Find an Partner by their UUID  # noqa: E501
        """
        pass

    def test_modify_active_campaign_for_bank_uuid(self):
        """Test case for modify_active_campaign_for_bank_uuid

        Start or stop a campaign  # noqa: E501
        """
        pass

    def test_update_bank_by_uuid(self):
        """Test case for update_bank_by_uuid

        Update the information of a single Partner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
