# coding: utf-8

"""
    SMApi

    SecurityMetrics' Application Programming Interface  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@securitymetrics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CampaignEmailWithoutLinks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'SelfLink',
        'email_type': 'str',
        'title': 'str',
        'uuid': 'str'
    }

    attribute_map = {
        'content': 'content',
        'email_type': 'email_type',
        'title': 'title',
        'uuid': 'uuid'
    }

    def __init__(self, content=None, email_type=None, title=None, uuid=None):  # noqa: E501
        """CampaignEmailWithoutLinks - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._email_type = None
        self._title = None
        self._uuid = None
        self.discriminator = None
        if content is not None:
            self.content = content
        if email_type is not None:
            self.email_type = email_type
        if title is not None:
            self.title = title
        if uuid is not None:
            self.uuid = uuid

    @property
    def content(self):
        """Gets the content of this CampaignEmailWithoutLinks.  # noqa: E501


        :return: The content of this CampaignEmailWithoutLinks.  # noqa: E501
        :rtype: SelfLink
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this CampaignEmailWithoutLinks.


        :param content: The content of this CampaignEmailWithoutLinks.  # noqa: E501
        :type: SelfLink
        """

        self._content = content

    @property
    def email_type(self):
        """Gets the email_type of this CampaignEmailWithoutLinks.  # noqa: E501

        The type for this Campaign Email Set.  # noqa: E501

        :return: The email_type of this CampaignEmailWithoutLinks.  # noqa: E501
        :rtype: str
        """
        return self._email_type

    @email_type.setter
    def email_type(self, email_type):
        """Sets the email_type of this CampaignEmailWithoutLinks.

        The type for this Campaign Email Set.  # noqa: E501

        :param email_type: The email_type of this CampaignEmailWithoutLinks.  # noqa: E501
        :type: str
        """

        self._email_type = email_type

    @property
    def title(self):
        """Gets the title of this CampaignEmailWithoutLinks.  # noqa: E501

        The title for this Campaign Email Set.  # noqa: E501

        :return: The title of this CampaignEmailWithoutLinks.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CampaignEmailWithoutLinks.

        The title for this Campaign Email Set.  # noqa: E501

        :param title: The title of this CampaignEmailWithoutLinks.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def uuid(self):
        """Gets the uuid of this CampaignEmailWithoutLinks.  # noqa: E501

        The Universal Unique IDentifier for this Campaign Email Set.  # noqa: E501

        :return: The uuid of this CampaignEmailWithoutLinks.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this CampaignEmailWithoutLinks.

        The Universal Unique IDentifier for this Campaign Email Set.  # noqa: E501

        :param uuid: The uuid of this CampaignEmailWithoutLinks.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CampaignEmailWithoutLinks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CampaignEmailWithoutLinks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
