# coding: utf-8

"""
    SMApi

    SecurityMetrics' Application Programming Interface  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: support@securitymetrics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataImportJobPost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dryrun': 'bool',
        'sheet_id': 'int'
    }

    attribute_map = {
        'dryrun': 'dryrun',
        'sheet_id': 'sheet_id'
    }

    def __init__(self, dryrun=None, sheet_id=None):  # noqa: E501
        """DataImportJobPost - a model defined in Swagger"""  # noqa: E501
        self._dryrun = None
        self._sheet_id = None
        self.discriminator = None
        if dryrun is not None:
            self.dryrun = dryrun
        self.sheet_id = sheet_id

    @property
    def dryrun(self):
        """Gets the dryrun of this DataImportJobPost.  # noqa: E501

        If True, just test that the data and field mappings are valid without actually addingmerchants  # noqa: E501

        :return: The dryrun of this DataImportJobPost.  # noqa: E501
        :rtype: bool
        """
        return self._dryrun

    @dryrun.setter
    def dryrun(self, dryrun):
        """Sets the dryrun of this DataImportJobPost.

        If True, just test that the data and field mappings are valid without actually addingmerchants  # noqa: E501

        :param dryrun: The dryrun of this DataImportJobPost.  # noqa: E501
        :type: bool
        """

        self._dryrun = dryrun

    @property
    def sheet_id(self):
        """Gets the sheet_id of this DataImportJobPost.  # noqa: E501

        The ID of the FileSheet to operate on  # noqa: E501

        :return: The sheet_id of this DataImportJobPost.  # noqa: E501
        :rtype: int
        """
        return self._sheet_id

    @sheet_id.setter
    def sheet_id(self, sheet_id):
        """Sets the sheet_id of this DataImportJobPost.

        The ID of the FileSheet to operate on  # noqa: E501

        :param sheet_id: The sheet_id of this DataImportJobPost.  # noqa: E501
        :type: int
        """
        if sheet_id is None:
            raise ValueError("Invalid value for `sheet_id`, must not be `None`")  # noqa: E501

        self._sheet_id = sheet_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataImportJobPost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataImportJobPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
